<?php
/**
 * Auto-generated menu data — do not edit by hand.
 * Source: web/src/data/demoProducts.ts
 *
 * @package Comptoir_Auguste
 */

declare(strict_types=1);

if (!defined('ABSPATH')) {
    exit;
}

function ca_categories(): array
{
    return [
        [
            'slug'        => 'formules',
            'name'        => 'Formules',
            'description' => 'Composez votre repas : entrée, plat et dessert.',
            'mosaic'      => 'formule-mosaique-v2.png',
            'showOnHome'  => true,
        ],
        [
            'slug'        => 'entrees',
            'name'        => 'Entrées',
            'description' => 'Pour commencer en douceur, tout fait maison.',
            'mosaic'      => 'entree-mosaique-v2.png',
            'showOnHome'  => true,
        ],
        [
            'slug'        => 'plats-du-moment',
            'name'        => 'Plats du moment',
            'description' => 'Plats généreux et cuisinés sur place.',
            'mosaic'      => 'plat-mosaique-v4.png',
            'showOnHome'  => true,
        ],
        [
            'slug'        => 'salades',
            'name'        => 'Salades repas',
            'description' => 'Des salades complètes, fraîches et méditerranéennes.',
            'mosaic'      => 'salade-mosaique-v2.png',
            'showOnHome'  => true,
        ],
        [
            'slug'        => 'snacking',
            'name'        => 'Snacking gourmand',
            'description' => 'Hors menu — sandwiches et gourmandises.',
            'mosaic'      => 'snacking-mosaique-v2.png',
            'showOnHome'  => true,
        ],
        [
            'slug'        => 'desserts',
            'name'        => 'Desserts',
            'description' => 'La touche sucrée, préparée avec soin.',
            'mosaic'      => 'dessert-mosaique-v4.png',
            'showOnHome'  => true,
        ],
        [
            'slug'        => 'boissons',
            'name'        => 'Boissons',
            'description' => 'Eaux, softs, jus, bières et vins de Provence.',
            'mosaic'      => 'boisson-mosaique-v2.png',
            'showOnHome'  => false,
        ],
        [
            'slug'        => 'boissons-chaudes',
            'name'        => 'Boissons chaudes',
            'description' => 'Cafés, chocolat chaud et thé.',
            'mosaic'      => 'boisson-chaude-mosaique-v2.png',
            'showOnHome'  => false,
        ]
    ];
}

function ca_products(): array
{
    return [
        [
            'slug'         => 'evian-33-cl',
            'name'         => 'Evian 33 cl',
            'description'  => 'Eau plate, servie bien fraîche.',
            'price'        => 2.1,
            'categorySlug' => 'boissons',
            'family'       => 'Eaux plates',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'evian-1-5-l',
            'name'         => 'Evian 1,5 L',
            'description'  => 'Eau plate, servie bien fraîche.',
            'price'        => 3.2,
            'categorySlug' => 'boissons',
            'family'       => 'Eaux plates',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'volvic-juicy-fraise-50-cl',
            'name'         => 'Volvic Juicy fraise 50 cl',
            'description'  => 'Eau plate, servie bien fraîche.',
            'price'        => 2.8,
            'categorySlug' => 'boissons',
            'family'       => 'Eaux plates',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'perrier-1-l',
            'name'         => 'Perrier 1 L',
            'description'  => 'Eau pétillante, servie bien fraîche.',
            'price'        => 3.2,
            'categorySlug' => 'boissons',
            'family'       => 'Eaux pétillantes',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'perrier-33-cl',
            'name'         => 'Perrier 33 cl',
            'description'  => 'Eau pétillante, servie bien fraîche.',
            'price'        => 2.1,
            'categorySlug' => 'boissons',
            'family'       => 'Eaux pétillantes',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'coca-cola-33-cl',
            'name'         => 'Coca Cola 33 cl',
            'description'  => 'Boisson fraîche, à déguster sur place ou à emporter.',
            'price'        => 2.4,
            'categorySlug' => 'boissons',
            'family'       => 'Sodas & softs',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'coca-cola-zero-33-cl',
            'name'         => 'Coca Cola Zero 33 cl',
            'description'  => 'Boisson fraîche, à déguster sur place ou à emporter.',
            'price'        => 2.4,
            'categorySlug' => 'boissons',
            'family'       => 'Sodas & softs',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'schweppes-agrumes-33-cl',
            'name'         => 'Schweppes agrumes 33 cl',
            'description'  => 'Boisson fraîche, à déguster sur place ou à emporter.',
            'price'        => 2.4,
            'categorySlug' => 'boissons',
            'family'       => 'Sodas & softs',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'schweppes-indian-tonic',
            'name'         => 'Schweppes Indian Tonic',
            'description'  => 'Boisson fraîche, à déguster sur place ou à emporter.',
            'price'        => 2.4,
            'categorySlug' => 'boissons',
            'family'       => 'Sodas & softs',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'sprite-33-cl',
            'name'         => 'Sprite 33 cl',
            'description'  => 'Boisson fraîche, à déguster sur place ou à emporter.',
            'price'        => 2.4,
            'categorySlug' => 'boissons',
            'family'       => 'Sodas & softs',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'oasis-tropical-33-cl',
            'name'         => 'Oasis Tropical 33 cl',
            'description'  => 'Boisson fraîche, à déguster sur place ou à emporter.',
            'price'        => 2.4,
            'categorySlug' => 'boissons',
            'family'       => 'Sodas & softs',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'oasis-pomme-cassis-framboise-33-cl',
            'name'         => 'Oasis Pomme Cassis Framboise 33 cl',
            'description'  => 'Boisson fraîche, à déguster sur place ou à emporter.',
            'price'        => 2.4,
            'categorySlug' => 'boissons',
            'family'       => 'Sodas & softs',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'fuzetea-peche-33-cl',
            'name'         => 'Fuzetea peche 33 cl',
            'description'  => 'Boisson fraîche, à déguster sur place ou à emporter.',
            'price'        => 2.4,
            'categorySlug' => 'boissons',
            'family'       => 'Sodas & softs',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'red-bull-25-cl',
            'name'         => 'Red bull 25 cl',
            'description'  => 'Boisson fraîche, à déguster sur place ou à emporter.',
            'price'        => 3,
            'categorySlug' => 'boissons',
            'family'       => 'Sodas & softs',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'red-bull-coco-acai-25-cl',
            'name'         => 'Red bull Coco Acai 25 cl',
            'description'  => 'Boisson fraîche, à déguster sur place ou à emporter.',
            'price'        => 3,
            'categorySlug' => 'boissons',
            'family'       => 'Sodas & softs',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'red-bull-pasteque-25-cl',
            'name'         => 'Red bull Pasteque 25 cl',
            'description'  => 'Boisson fraîche, à déguster sur place ou à emporter.',
            'price'        => 3,
            'categorySlug' => 'boissons',
            'family'       => 'Sodas & softs',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'kombucha-feuille-de-cassis-bio-33-cl',
            'name'         => 'Kombucha feuille de cassis BIO 33 cl',
            'description'  => 'Boisson fraîche, à déguster sur place ou à emporter.',
            'price'        => 3.9,
            'categorySlug' => 'boissons',
            'family'       => 'Sodas & softs',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'kombucha-feuille-clementine-bio-33-cl',
            'name'         => 'Kombucha feuille clémentine BIO 33 cl',
            'description'  => 'Boisson fraîche, à déguster sur place ou à emporter.',
            'price'        => 3.9,
            'categorySlug' => 'boissons',
            'family'       => 'Sodas & softs',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'uma-limonade-bio-33cl',
            'name'         => 'UMA limonade Bio 33cl',
            'description'  => 'Boisson fraîche, à déguster sur place ou à emporter.',
            'price'        => 3,
            'categorySlug' => 'boissons',
            'family'       => 'Sodas & softs',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'kookabarra-ananas-25-cl',
            'name'         => 'KOOKABARRA Ananas 25 cl',
            'description'  => 'Jus de fruits premium, format individuel.',
            'price'        => 3.2,
            'categorySlug' => 'boissons',
            'family'       => 'Jus de fruits',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'kookabarra-multifruits-25-cl',
            'name'         => 'KOOKABARRA Multifruits 25 cl',
            'description'  => 'Jus de fruits premium, format individuel.',
            'price'        => 3.2,
            'categorySlug' => 'boissons',
            'family'       => 'Jus de fruits',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'kookabarra-orange',
            'name'         => 'KOOKABARRA Orange',
            'description'  => 'Jus de fruits premium, format individuel.',
            'price'        => 3.2,
            'categorySlug' => 'boissons',
            'family'       => 'Jus de fruits',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'kookabarra-pamplemousse',
            'name'         => 'KOOKABARRA Pamplemousse',
            'description'  => 'Jus de fruits premium, format individuel.',
            'price'        => 3.2,
            'categorySlug' => 'boissons',
            'family'       => 'Jus de fruits',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'kookabarra-pomme-pink-lady',
            'name'         => 'KOOKABARRA Pomme Pink Lady',
            'description'  => 'Jus de fruits premium, format individuel.',
            'price'        => 3.2,
            'categorySlug' => 'boissons',
            'family'       => 'Jus de fruits',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'kookabarra-detox-pomme-mangue-gingembre',
            'name'         => 'KOOKABARRA Detox Pomme mangue gingembre',
            'description'  => 'Jus de fruits premium, format individuel.',
            'price'        => 3.2,
            'categorySlug' => 'boissons',
            'family'       => 'Jus de fruits',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'kookabarra-detox-pomme-citron-vert-charbon-vegetal',
            'name'         => 'KOOKABARRA Detox Pomme citron vert charbon vegetal',
            'description'  => 'Jus de fruits premium, format individuel.',
            'price'        => 3.2,
            'categorySlug' => 'boissons',
            'family'       => 'Jus de fruits',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'fanny-biere-blanche-artisanale-bio-33-cl',
            'name'         => 'FANNY biere blanche artisanale BIO 33 cl',
            'description'  => 'Bière artisanale bio Fanny, 33 cl.',
            'price'        => 4.4,
            'categorySlug' => 'boissons',
            'family'       => 'Bières',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'fanny-biere-blonde-artisanale-bio-33-cl',
            'name'         => 'FANNY biere blonde artisanale BIO 33 cl',
            'description'  => 'Bière artisanale bio Fanny, 33 cl.',
            'price'        => 4.4,
            'categorySlug' => 'boissons',
            'family'       => 'Bières',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'fanny-fruits-rouges-artisanale-bio-33-cl',
            'name'         => 'FANNY Fruits rouges artisanale BIO 33 cl',
            'description'  => 'Bière artisanale bio Fanny, 33 cl.',
            'price'        => 4.4,
            'categorySlug' => 'boissons',
            'family'       => 'Bières',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'cuvee-1992-blanc-aoc-cotes-de-provence-75-cl',
            'name'         => 'CUVEE 1992 Blanc AOC Cotes de provence 75 cl',
            'description'  => 'Vin AOC Côtes de Provence, cuvée 1992, 75 cl.',
            'price'        => 21,
            'categorySlug' => 'boissons',
            'family'       => 'Vins',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'cuvee-1992-rose-aoc-cotes-de-provence-75-cl',
            'name'         => 'CUVEE 1992 Rose AOC Cotes de provence 75 cl',
            'description'  => 'Vin AOC Côtes de Provence, cuvée 1992, 75 cl.',
            'price'        => 21,
            'categorySlug' => 'boissons',
            'family'       => 'Vins',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'cuvee-1992-rouge-aoc-cotes-de-provence-75-cl',
            'name'         => 'CUVEE 1992 Rouge AOC Cotes de provence 75 cl',
            'description'  => 'Vin AOC Côtes de Provence, cuvée 1992, 75 cl.',
            'price'        => 21,
            'categorySlug' => 'boissons',
            'family'       => 'Vins',
            'image'        => 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'oeuf-mimosa-a-la-mayonnaise-maison',
            'name'         => 'Œufs mimosa à la mayonnaise maison',
            'description'  => 'Œufs mimosa et mayonnaise maison.',
            'price'        => 4.3,
            'categorySlug' => 'entrees',
            'family'       => 'Entrées',
            'image'        => ca_brand('dishes/oeufs-mimosa.jpg'),
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'salade-de-lentilles-mediterraneenne',
            'name'         => 'Salade de lentilles méditerranéenne',
            'description'  => 'lentilles, feta, tomates, échalote, persil.',
            'price'        => 4.3,
            'categorySlug' => 'entrees',
            'family'       => 'Entrées',
            'image'        => 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'caviar-d-aubergine-a-la-provencale-et-ses-croutons',
            'name'         => 'Caviar d\'aubergine à la provençale et ses croutons',
            'description'  => 'Aubergines grillées, cumin, ail, citron, huile d\'olive.',
            'price'        => 4.3,
            'categorySlug' => 'entrees',
            'family'       => 'Entrées',
            'image'        => ca_brand('dishes/caviar-aubergine.jpg'),
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'encornets-farcis-a-la-provencale',
            'name'         => 'Encornets farcis à la provençale et riz',
            'description'  => 'Encornets farcis, sauce tomate provençale, riz.',
            'price'        => 11.9,
            'categorySlug' => 'plats-du-moment',
            'family'       => 'Plats du moment',
            'image'        => ca_brand('dishes/encornets-farcis.jpg'),
            'badge'        => 'du-jour',
            'featured'     => true,
        ],
        [
            'slug'         => 'couscous-au-poulet-et-ses-legumes',
            'name'         => 'Couscous au poulet et ses légumes',
            'description'  => 'Poulet, semoule, pois chiche, carotte, navet, courgette.',
            'price'        => 11.9,
            'categorySlug' => 'plats-du-moment',
            'family'       => 'Plats du moment',
            'image'        => ca_brand('dishes/couscous-poulet.jpg'),
            'badge'        => null,
            'featured'     => true,
        ],
        [
            'slug'         => 'hachis-parmentier-au-canard-confit-a-la-creme-de-parmesan',
            'name'         => 'Hachis parmentier au canard confit à la crème de parmesan',
            'description'  => 'Hachis parmentier au canard confit, sublimé par une crème de parmesan.',
            'price'        => 11.9,
            'categorySlug' => 'plats-du-moment',
            'family'       => 'Plats du moment',
            'image'        => 'https://images.unsplash.com/photo-1432139509613-5c4255815697?auto=format&fit=crop&w=900&q=80',
            'badge'        => 'du-jour',
            'featured'     => false,
        ],
        [
            'slug'         => 'pave-de-saumon-sur-son-lit-de-confit-de-legumes',
            'name'         => 'Pavé de saumon sur son lit de confit de légumes',
            'description'  => 'Saumon grillé, tian de légumes confits au four.',
            'price'        => 11.9,
            'categorySlug' => 'plats-du-moment',
            'family'       => 'Plats du moment',
            'image'        => ca_brand('dishes/saumon.jpg'),
            'badge'        => 'de-saison',
            'featured'     => false,
        ],
        [
            'slug'         => 'la-paysanne',
            'name'         => 'La Paysanne',
            'description'  => 'lard grillé, pommes de terre grenaille, légumes grillés, salade, olives noires, vinaigrette à l\'échalote.',
            'price'        => 11.9,
            'categorySlug' => 'salades',
            'family'       => 'Salades repas',
            'image'        => ca_brand('dishes/salade-paysanne.jpg'),
            'badge'        => null,
            'featured'     => true,
        ],
        [
            'slug'         => 'la-mediterraneenne',
            'name'         => 'La Méditerranéenne',
            'description'  => 'Thon, œuf, haricots verts, poivrons grillés, oignons rouges, tomates, salade, vinaigrette à l\'huile d\'olive.',
            'price'        => 11.9,
            'categorySlug' => 'salades',
            'family'       => 'Salades repas',
            'image'        => ca_brand('dishes/salade-mediterraneenne-v2.jpg'),
            'badge'        => null,
            'featured'     => true,
        ],
        [
            'slug'         => 'l-auguste',
            'name'         => 'L\'Auguste',
            'description'  => 'Poulpe, pommes de terre, fenouil, cebette, persil, pointe d\'ail, tomates confites, câpres, vinaigrette citron à l\'huile d\'olive.',
            'price'        => 11.9,
            'categorySlug' => 'salades',
            'family'       => 'Salades repas',
            'image'        => ca_brand('dishes/salade-auguste-v2.jpg'),
            'badge'        => 'signature',
            'featured'     => true,
        ],
        [
            'slug'         => 'lobster-roll',
            'name'         => 'Lobster Roll',
            'description'  => 'pain brioché, émincé de poulpe, tomates confites, salade, pickles d\'oignons, mayonnaise aux herbes.',
            'price'        => 7.9,
            'categorySlug' => 'snacking',
            'family'       => 'Snacking gourmand',
            'image'        => ca_brand('dishes/lobster-roll.jpg'),
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'club',
            'name'         => 'Club',
            'description'  => 'pain aux céréales, poulet, œufs, bacon, salade, tomates, mayonnaise pointe de curry.',
            'price'        => 5.4,
            'categorySlug' => 'snacking',
            'family'       => 'Snacking gourmand',
            'image'        => 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'madame-truffe',
            'name'         => 'Madame Truffe',
            'description'  => 'pain de mie, jambon blanc, comté, béchamel à la truffe.',
            'price'        => 6.9,
            'categorySlug' => 'snacking',
            'family'       => 'Snacking gourmand',
            'image'        => 'https://images.unsplash.com/photo-1528736235302-52922df5c122?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'tarte-salee',
            'name'         => 'Tarte salée',
            'description'  => 'chèvre frais, courgettes, tomates séchées, œuf, crème fraiche et salade.',
            'price'        => 8.9,
            'categorySlug' => 'snacking',
            'family'       => 'Snacking gourmand',
            'image'        => 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'fondant-au-chocolat-et-sa-creme-anglaise',
            'name'         => 'Fondant au chocolat et sa crème anglaise',
            'description'  => 'Fondant au chocolat et sa crème anglaise.',
            'price'        => 4.7,
            'categorySlug' => 'desserts',
            'family'       => 'Desserts',
            'image'        => ca_brand('dishes/fondant-chocolat.jpg'),
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'tarte-aux-pommes',
            'name'         => 'Tarte aux pommes',
            'description'  => 'Tarte aux pommes maison.',
            'price'        => 4.7,
            'categorySlug' => 'desserts',
            'family'       => 'Desserts',
            'image'        => 'https://images.unsplash.com/photo-1568571780765-9276ac8b75f0?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'blanc-manger-aux-abricots-infuses-au-romarin',
            'name'         => 'Blanc-manger aux abricots infusés au romarin',
            'description'  => 'Blanc-manger aux abricots infusés au romarin.',
            'price'        => 4.7,
            'categorySlug' => 'desserts',
            'family'       => 'Desserts',
            'image'        => 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'fromage-blanc-marmelade-de-fruits-rouges',
            'name'         => 'Fromage blanc, marmelade de fruits rouges',
            'description'  => 'Fromage blanc et marmelade de fruits rouges.',
            'price'        => 4.7,
            'categorySlug' => 'desserts',
            'family'       => 'Desserts',
            'image'        => 'https://images.unsplash.com/photo-1488477304112-4944851de5d0?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'cookie-trois-chocolats-et-noix',
            'name'         => 'Cookie trois chocolats et noix',
            'description'  => 'Cookie aux trois chocolats et aux noix.',
            'price'        => 3.5,
            'categorySlug' => 'desserts',
            'family'       => 'Desserts',
            'image'        => 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'entree-plat-dessert',
            'name'         => 'Entrée + Plat + Dessert',
            'description'  => 'Formule complète : une entrée, un plat et un dessert au choix.',
            'price'        => 20.9,
            'categorySlug' => 'formules',
            'family'       => 'Formules',
            'image'        => 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=900&q=80',
            'badge'        => 'signature',
            'featured'     => true,
        ],
        [
            'slug'         => 'entree-plat',
            'name'         => 'Entrée + Plat',
            'description'  => 'Formule entrée et plat au choix.',
            'price'        => 16.2,
            'categorySlug' => 'formules',
            'family'       => 'Formules',
            'image'        => 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'plat-dessert',
            'name'         => 'Plat + Dessert',
            'description'  => 'Formule plat et dessert au choix.',
            'price'        => 16.9,
            'categorySlug' => 'formules',
            'family'       => 'Formules',
            'image'        => 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'espresso-6-cl',
            'name'         => 'Espresso 6 cl',
            'description'  => 'Espresso serré.',
            'price'        => 1.7,
            'categorySlug' => 'boissons-chaudes',
            'family'       => 'Cafés & infusions',
            'image'        => 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'allonge-10-cl',
            'name'         => 'Allongé 10 cl',
            'description'  => 'Café allongé.',
            'price'        => 1.7,
            'categorySlug' => 'boissons-chaudes',
            'family'       => 'Cafés & infusions',
            'image'        => 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'noisette-6-cl',
            'name'         => 'Noisette 6 cl',
            'description'  => 'Café noisette.',
            'price'        => 1.9,
            'categorySlug' => 'boissons-chaudes',
            'family'       => 'Cafés & infusions',
            'image'        => 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'cappuccino-15-cl',
            'name'         => 'Cappuccino 15 cl',
            'description'  => 'Cappuccino crémeux.',
            'price'        => 2.8,
            'categorySlug' => 'boissons-chaudes',
            'family'       => 'Cafés & infusions',
            'image'        => 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'chocolat-chaud-15-cl',
            'name'         => 'Chocolat chaud 15 cl',
            'description'  => 'Chocolat chaud onctueux.',
            'price'        => 2.8,
            'categorySlug' => 'boissons-chaudes',
            'family'       => 'Cafés & infusions',
            'image'        => 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ],
        [
            'slug'         => 'the',
            'name'         => 'Thé',
            'description'  => 'Thé chaud, infusion au choix.',
            'price'        => 2.6,
            'categorySlug' => 'boissons-chaudes',
            'family'       => 'Cafés & infusions',
            'image'        => 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80',
            'badge'        => null,
            'featured'     => false,
        ]
    ];
}

function ca_featured_products(): array
{
    return array_values(array_filter(ca_products(), static fn(array $p): bool => !empty($p['featured'])));
}

function ca_moment_products(): array
{
    $plats = array_values(array_filter(
        ca_products(),
        static fn(array $p): bool => ($p['categorySlug'] ?? '') === 'plats-du-moment' && !empty($p['featured'])
    ));
    $salades = array_values(array_filter(
        ca_products(),
        static fn(array $p): bool => ($p['categorySlug'] ?? '') === 'salades' && !empty($p['featured'])
    ));

    return array_slice(array_merge(array_slice($plats, 0, 3), $salades), 0, 6);
}

function ca_home_categories(): array
{
    return array_values(array_filter(
        ca_categories(),
        static fn(array $c): bool => ($c['showOnHome'] ?? true) !== false
    ));
}
